// <auto-generated />
namespace Tivoli.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class hr4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hr4));
        
        string IMigrationMetadata.Id
        {
            get { return "202305131801254_hr4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
